In [2]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array)	

[[1 2 3]
 [4 5 6]]


In [6]:
my_array.shape

(2, 3)

In [7]:
my_array.shape=(3,2)